// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVpXU7tiECTlrqhbfiS7esREkwViKcWpY',
    appId: '1:1052201832170:web:5ce1ccac37340672dad193',
    messagingSenderId: '1052201832170',
    projectId: 'ecs-services',
    authDomain: 'ecs-services.firebaseapp.com',
    storageBucket: 'ecs-services.firebasestorage.app',
    measurementId: 'G-GTYGLZ7CJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv7Diq562oIWQBcSfWYseNIOkrfw3kF4Q',
    appId: '1:312663527364:android:3e166353a97da29af81e91',
    messagingSenderId: '312663527364',
    projectId: 'sis-india',
    storageBucket: 'sis-india.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7G9BK8Yue_22BC_vpZiS6YQ0A1cI3wsk',
    appId: '1:312663527364:ios:8825ea9584cd0f8ef81e91',
    messagingSenderId: '312663527364',
    projectId: 'sis-india',
    storageBucket: 'sis-india.firebasestorage.app',
    iosBundleId: 'com.sisindia.mysis.guard', // 👈 updated bundle id
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl-Z4gMKH1VIpRyiRuTgc300hGO1gqPh4',
    appId: '1:1052201832170:ios:ea6f735372e72807dad193',
    messagingSenderId: '1052201832170',
    projectId: 'ecs-services',
    storageBucket: 'ecs-services.firebasestorage.app',
    iosBundleId: 'com.sisindia.mysis.guard', // 👈 updated bundle id
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVpXU7tiECTlrqhbfiS7esREkwViKcWpY',
    appId: '1:1052201832170:web:ab9ab3e098a415bddad193',
    messagingSenderId: '1052201832170',
    projectId: 'ecs-services',
    authDomain: 'ecs-services.firebaseapp.com',
    storageBucket: 'ecs-services.firebasestorage.app',
    measurementId: 'G-59DBZEPPNC',
  );

}